name: CI

on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  DEV: false
  PROD: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/checkout@v3

      - name: install
        run: pnpm install --frozen-lockfile

      - name: build
        run: pnpm run build
      
      - name: post-build
        run: pnpm run post-build
        
      - name: deploy pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: publish-github
          folder: dist/public
